---
- name: add java repo
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
  register: result

- name: add java key
  apt_key: id=EEA14886 keyserver=keyserver.ubuntu.com state=present

- name: update apt cache
  apt: update_cache=yes
  when: result|changed

- name: apply java license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install java
  apt: name=oracle-java8-installer state=present