---
- name: Install aptitude using apt
  become: yes
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- debug:
    msg:  Install aptitude using apt

- name: Install required system packages
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'bash', 'openssl', 'libssl-dev', 'libssl-doc', 'postgresql' , 'postgresql-contrib', 'postgresql-client', 'libpq-dev', 'openjdk-8-jdk' ]

- debug: 
    msg: Execute the script

- name: example copying file with owner and permissions
  become: yes
  copy:
    src: /tmp/transaction.tar
    dest: /tmp/transaction.tar

- name: unarchive the tar
  become: yes
  unarchive:
    src: /tmp/transaction.tar
    dest: /tmp
    remote_src: True

- name: Execute liquibase to install database
  become: yes
  command: chdir=/tmp/transaction sh liquibase --driver=org.postgresql.Driver --changeLogFile=./changelog-master-transaction.xml --url="jdbc:postgresql://localhost:5432/transaction" --username=postgres --password=crosstown update
