---
- hosts: webserver1
  tags: webserver1-configuration
  roles: 
    - { role: instal-docker, tags: 'instal-docker' }
    - { role: deploy_billpay, tags: 'deploy_billpay' }


- hosts: webserver2
  roles:
  tags: webserver2-configuration
    - { role: instal-docker, tags: 'instal-docker' }
    - { role: deploy_statement, tags: 'deploy_statement' }

- hosts: database
  tags: db-configuration
  roles: 
    - { role: install-postgres, tags: 'install-postgres' }
     
