---
- hosts: webserver1
  roles: 
    - { role: instal-docker, tags: 'instal-docker' }


- hosts: webserver2
  roles:
    - { role: instal-docker, tags: 'instal-docker' }

- hosts: database
  tags: db-configuration
  roles: 
    - { role: install-postgres, tags: 'install-postgres' }
     
