---
- hosts: webserver1
  roles: 
    - { role: instal-docker, tags: 'instal-docker' }


- hosts: webserver2
  roles:
    - { role: instal-docker, tags: 'instal-docker' }

- hosts: database
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  roles:
    - createdb
    - liquibase
    - java
    - {role: instal-docker, tags: 'instal-docker'}
     

